export const ALL_PRODUCT_REQUEST="ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL"

export const PRODUCTDETAIL_PRODUCT_REQUEST="PRODUCTDETAIL_PRODUCT_REQUEST"
export const PRODUCTDETAIL_PRODUCT_SUCCESS="PRODUCTDETAIL_PRODUCT_SUCCESS"
export const PRODUCTDETAIL_PRODUCT_FAIL="PRODUCTDETAIL_PRODUCT_FAIL"
export const CLEAR_ERROR="CLEAR_ERROR"